VoteForCause/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('summernote/', include('django_summernote.urls')),
]

handler404 = "core.views.error_404"
# handler500 = "core.views.error_500"

core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # path('', views.home, name='home'),
    path("", views.home, name="home"),
    path("search/", views.search_for_cause, name='search'),
    # path("browse/", views.search_for_cause, name='search'),
    path('cause/user/<username>/', views.user_cause, name='user_cause'),
    path("tag/<tag_slug>/", views.tag_view, name="tag_view"),
    path("cause/create/", views.create_cause, name="create_cause"),
    path("cause/<slug>/", views.cause_detail, name="cause_detail"),
    path("cause/signed/<slug>/", views.cause_signed_userlist, name="cause_sign_list"),
    path("cause/update/<slug>/", views.cause_update, name="update_cause"),
    path("cause/delete/<slug>/", views.cause_delete, name="delete_cause"),
    path("cause/sign/add/<slug>/", views.add_sign_cause, name='add_sign'),
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="account_login"),
    path("logout/", views.CustomLogoutView.as_view(), name="account_logout"),
    path("profile/", views.ProfileView, name="profile"),
    path("signup/", views.CustomSignupView.as_view(), name="account_signup"),
    # path('password/change/', views.CustomPasswordChangeView.as_view(),
    # name='account_change_password'),
]

core/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save
from datetime import datetime
from taggit.managers import TaggableManager
from bs4 import BeautifulSoup


class CauseManager(models.Manager):
    def get_queryset(self):
        return super(CauseManager, self).get_queryset().filter(active=True)


AVG_SPEED = 250


class Causes(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField(null=True, blank=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    # auto_now_add, add the time we saved initially
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager(help_text='Select any of the tags related to the cause')
    sign_count = models.PositiveIntegerField(default=0)
    '''
    sign_count will be updated everytime a voteforcause is saved, so that I can know the number 
    of signature added for each cause.'''
    reading_time = models.PositiveIntegerField(default=0)

    objects = models.Manager()
    published = CauseManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ("-id",)
        verbose_name_plural = "Causes"

    def get_absolute_url(self):
        return reverse("cause_detail", args=[self.slug])


@receiver(pre_save, sender=Causes)

def create_slug_field(sender, instance, **kwargs):
    '''To be run everytime before a save method is called on Cause, it will set the calculated value
    of the reading time
    '''
    obj = BeautifulSoup(instance.body, 'html.parser')
    obj_len = len(obj.text.split(' '))
    instance.reading_time = obj_len / AVG_SPEED
    # instance.reading_time =


class VoteForCause(models.Model):
    cause = models.ForeignKey(Causes, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # count = models.PositiveIntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)
    has_signed = models.BooleanField(default=False)

    def __str__(self):
        return f'{str(self.cause)}'

    @property
    def time_diff(self):
        time = datetime.now()
        if self.timestamp.day == time.day:
            return str(time.hour - self.timestamp.hour) + " hours ago"
        else:
            if self.timestamp.month == time.month:
                return str(time.day - self.timestamp.day) + " days ago"
            else:
                if self.timestamp.year == time.year:
                    return str(time.month - self.timestamp.month) + " months ago"
        return self.timestamp

    class Meta:
        unique_together = ['cause', 'user']


@receiver(post_save, sender=VoteForCause)
def cause_sign_count_increment(sender, instance, created, **kwargs):
    '''
    The signal that will be runned after a user has voted for a particular cause, it will run on
    the causes itself, so as to increment the value of sign_count in the Causes.
    '''
    if created:
        instance.cause.sign_count += 1
        instance.cause.save()

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.conf import settings
from django.dispatch import receiver
from django_countries.fields import CountryField


class CustomUser(AbstractUser):
    pass


class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=11)
    nationality = CountryField()

    def __str__(self):
        return str(self.user) + " Profile"

    class Meta:
        ordering = ("-id",)
        verbose_name_plural = "Profile"


@receiver(post_save, sender=settings.AUTH_USER_MODEL)  # add this
def create_user_profile(sender, instance, created, **kwargs):
    '''This signal will be run after saving a new user, its job is to create a profile for
    such a user.'''
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)

def save_user_profile(sender, instance, **kwargs):
    '''
    save the profile created by the signal above
    '''
    instance.profile.save()

users/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserChangeForm,
    UserCreationForm,
    get_user_model,
    AuthenticationForm,
)
from allauth.account.forms import LoginForm, SignupForm, ChangePasswordForm
from users.models import Profile
from django_countries.widgets import CountrySelectWidget
from django_countries.fields import CountryField

CustomUser = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        models = CustomUser
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        models = CustomUser
        fields = UserCreationForm.Meta.fields


class CustomRegistrationForm(SignupForm):
    def __init__(self, *args, **kwargs):
        # self.request = kwargs.pop('request', None)
        super(CustomRegistrationForm, self).__init__(*args, **kwargs)
        # self.fields["username"].widget.attrs["placeholder"] = "username..."
        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields["username"].label = ""

        # self.fields["email"].widget.attrs["placeholder"] = "E-mail..."
        self.fields["email"].widget.attrs["class"] = "form-control"
        self.fields["email"].label = ""
        self.fields["email"].widget.attrs["required"] = "required"

        # self.fields["password1"].widget.attrs["placeholder"] = "your password..."
        self.fields["password1"].widget.attrs["class"] = "form-control"
        self.fields["password1"].label = ""

        # self.fields["password2"].widget.attrs["placeholder"] = "your password again..."
        self.fields["password2"].widget.attrs["class"] = "form-control"
        self.fields["password2"].label = ""


class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        # self.request = kwargs.pop('request', None)
        super(CustomLoginForm, self).__init__(*args, **kwargs)

        # self.fields["login"].widget.attrs["placeholder"] = "username..."
        self.fields["login"].widget.attrs["class"] = "form-control"
        self.fields["login"].label = ""

        # self.fields["password"].widget.attrs["placeholder"] = "password..."
        self.fields["password"].widget.attrs["class"] = "form-control"
        self.fields["password"].label = ""


class CustomPasswordChange(ChangePasswordForm):
    def __init__(self, *args, **kwargs):
        # self.request = kwargs.pop('request', None)
        super(CustomPasswordChange, self).__init__(*args, **kwargs)

        self.fields["oldpassword"].widget.attrs["placeholder"] = "current password ..."
        self.fields["oldpassword"].widget.attrs["class"] = "form-control"
        self.fields["oldpassword"].label = ""

        self.fields["password1"].widget.attrs["placeholder"] = "new password..."
        self.fields["password1"].widget.attrs["class"] = "form-control"
        self.fields["password1"].label = ""

        self.fields["password2"].widget.attrs["placeholder"] = "new password again..."
        self.fields["password2"].widget.attrs["class"] = "form-control"
        self.fields["password2"].label = ""


from allauth.account.forms import ResetPasswordForm


def CustomPasswordReset(ResetPasswordForm):
    email = forms.EmailField()


class ProfileForm(forms.ModelForm):
    country = CountryField(blank_label="(select country)")

    class Meta:
        model = Profile
        fields = ["phone_number", "nationality"]
        widgets = {"country": CountrySelectWidget()}

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        # self.fields["password1"].widget.attrs["placeholder"] = "your password..."
        self.fields["phone_number"].widget.attrs["required"] = "required"
        # self.fields['phone_number'].label = ''

        # self.fields["password1"].widget.attrs["placeholder"] = "your password..."
        self.fields["nationality"].widget.attrs["required"] = "required"
        # self.fields['phone_number'].label = ''


class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ("username", "first_name", "last_name", "email")

    def __init__(self, *args, **kwargs):
        super(CustomUserForm, self).__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs["required"] = "required"
        self.fields["last_name"].widget.attrs["required"] = "required"
        self.fields["email"].widget.attrs["required"] = "required"

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib import messages
from django.urls import reverse_lazy
from allauth.account.views import PasswordChangeView, LoginView, SignupView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ProfileForm, CustomUserForm, CustomPasswordChange
from django.contrib.auth.decorators import login_required


class CustomLoginView(LoginView):
    """
    inheriting from the allauth LoginView,
    """

    template_name = "account/login.html"
    # success_url = reverse_lazy('profile')
    redirect_field_name = "next"


class CustomLogoutView(LogoutView):
    # template_name = 'account/logout.html'
    success_url = "account_login"

    def post(self, request):
        logout(request)
        return redirect("account_login")

    def get(self, request):
        return render(request, "account/logout.html")


class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    def get_success_url(self):
        success_url = reverse_lazy("home")
        messages.info(self.request, "Password changed succesfully")
        return success_url


@login_required
def ProfileView(request):
    user = request.user
    if request.method == "POST":
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        user_form = CustomUserForm(request.POST, instance=request.user)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.warning(request, 'You can now start creating Cause!')
        else:
            messages.warning(request, "Error filling the form")
        return redirect("profile")
    else:
        profile_form = ProfileForm(instance=request.user.profile)
        user_form = CustomUserForm(instance=request.user)
    return render(
        request,
        "profile.html",
        {
            "profile_form": profile_form,
            "user_form": user_form,
            "user": user,
        },
    )


# def custom_signup_view(request):
#     User = get_user_model()
#     if request.method == 'POST':
#         user_form = CustomRegistrationForm(request.POST)
#         profile_form = ProfileForm(request.POST)
#         if user_form.is_valid():
#             username = user_form.cleaned_data['username']
#             print('username ', username)
#             if profile_form.is_valid():
#                 phone_number = profile_form.cleaned_data['phone_number']
#                 print(phone_number)
#             # return redirect(reverse_lazy('account_login'))
#         else:
#             print('Errorrooo')
#             # return render(request, 'account/signup.html', {'user_form': user_form,
#             #                                                'profile_form': profile_form})
#     else:
#         user_form = CustomRegistrationForm()
#         profile_form = ProfileForm()
#
#     return render(request, 'account/signup.html', {'user_form': user_form,
#                                                    'profile_form': profile_form})


class CustomSignupView(SignupView):
    template_name = "account/signup.html"
    redirect_field_name = "next"

    def dispatch(self, request, *args, **kwargs):
        # will redirect to the home page if a user tries to access the register page while logged in
        if request.user.is_authenticated:
            return redirect("home")

        # else process dispatch as it otherwise normally would
        return super(CustomSignupView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.user = form.save(self.request)
        messages.info(self.request, "Registration Successfull, Login...")
        return redirect("account_login")

users/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <!--User-->
    <br><br>
    <div class="container mx-auto">
        <div class="row">
            <div class="col-sm-12 col-md-10 col-lg-8 offset-lg-2 offset-md-1 pb-4">
                <div class="card p-4">
                    <h4 class="card-title font-weight-bold text-center">
                        Hello, {{ user.username|title }}</h4>
                    <hr>
                    <div class="card-text">
                        <p class="text-muted mb-0" style="font-size: 12px">Username:</p>
                        <p>{{ user.username }}</p>
                        <p class="text-muted mb-0" style="font-size: 12px">Name:</p>
                        <p>{{ user.first_name }} {{ user.last_name }}</p>
                        <p class="text-muted mb-0" style="font-size: 12px">Email:</p>
                        <p>{{ user.email }} </p>
                        <p class="text-muted mb-0" style="font-size: 12px">Phone Number:</p>
                        <p>{{ user.profile.phone_number }}</p>
                        <p class="text-muted mb-0" style="font-size: 12px">Nationality:</p>
                        <p>{{ user.profile.nationality }}</p>
                        <p class="text-muted mb-0" style="font-size: 12px">Email:</p>
                        <p>{{ user.email }} </p>
                        <p class="text-muted mb-0" style="font-size: 12px">No. of Causes
                            Created:</p>
                        <p>{{ user.causes_set.all.count }} Cause{{ user.causes_set.all.count|pluralize }} <a class="btn btn-sm
                            btn-info" href="{% url 'user_cause' user %}">View All</a></p>
                        <div class="text-right">
                            <button type="button" class="btn btn-outline-primary btn-sm"
                                    data-toggle="modal" data-target="#profileModal">Edit Profile
                            </button>
                            <a class="btn btn-outline-danger btn-sm"
                               href="{% url 'account_change_password' %}">Change
                                Password</a>
                        </div>

                    </div>
                </div>

            </div>
            <!--Edit user modal-->
            <div class="modal fade" tabindex="-1" id="profileModal" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Edit Profile</h5>
                            <button type="button" class="close" data-dismiss="modal"
                                    aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form method="post">
                                {% csrf_token %}
                                {{ profile_form | crispy }}
                                {{ user_form | crispy }}
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Save changes</button>

                            </form>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    </div>

{% endblock %}