VoteForCause/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('summernote/', include('django_summernote.urls')),
]

handler404 = "core.views.error_404"
# handler500 = "core.views.error_500"

core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # path('', views.home, name='home'),
    path("", views.home, name="home"),
    path("search/", views.search_for_cause, name='search'),
    # path("browse/", views.search_for_cause, name='search'),
    path('cause/user/<username>/', views.user_cause, name='user_cause'),
    path("tag/<tag_slug>/", views.tag_view, name="tag_view"),
    path("cause/create/", views.create_cause, name="create_cause"),
    path("cause/<slug>/", views.cause_detail, name="cause_detail"),
    path("cause/signed/<slug>/", views.cause_signed_userlist, name="cause_sign_list"),
    path("cause/update/<slug>/", views.cause_update, name="update_cause"),
    path("cause/delete/<slug>/", views.cause_delete, name="delete_cause"),
    path("cause/sign/add/<slug>/", views.add_sign_cause, name='add_sign'),
]

core/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save
from datetime import datetime
from taggit.managers import TaggableManager
from bs4 import BeautifulSoup


class CauseManager(models.Manager):
    def get_queryset(self):
        return super(CauseManager, self).get_queryset().filter(active=True)


AVG_SPEED = 250


class Causes(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField(null=True, blank=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    # auto_now_add, add the time we saved initially
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager(help_text='Select any of the tags related to the cause')
    sign_count = models.PositiveIntegerField(default=0)
    '''
    sign_count will be updated everytime a voteforcause is saved, so that I can know the number 
    of signature added for each cause.'''
    reading_time = models.PositiveIntegerField(default=0)

    objects = models.Manager()
    published = CauseManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ("-id",)
        verbose_name_plural = "Causes"

    def get_absolute_url(self):
        return reverse("cause_detail", args=[self.slug])


@receiver(pre_save, sender=Causes)

def create_slug_field(sender, instance, **kwargs):
    '''To be run everytime before a save method is called on Cause, it will set the calculated value
    of the reading time
    '''
    obj = BeautifulSoup(instance.body, 'html.parser')
    obj_len = len(obj.text.split(' '))
    instance.reading_time = obj_len / AVG_SPEED
    # instance.reading_time =


class VoteForCause(models.Model):
    cause = models.ForeignKey(Causes, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # count = models.PositiveIntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)
    has_signed = models.BooleanField(default=False)

    def __str__(self):
        return f'{str(self.cause)}'

    @property
    def time_diff(self):
        time = datetime.now()
        if self.timestamp.day == time.day:
            return str(time.hour - self.timestamp.hour) + " hours ago"
        else:
            if self.timestamp.month == time.month:
                return str(time.day - self.timestamp.day) + " days ago"
            else:
                if self.timestamp.year == time.year:
                    return str(time.month - self.timestamp.month) + " months ago"
        return self.timestamp

    class Meta:
        unique_together = ['cause', 'user']


@receiver(post_save, sender=VoteForCause)
def cause_sign_count_increment(sender, instance, created, **kwargs):
    '''
    The signal that will be runned after a user has voted for a particular cause, it will run on
    the causes itself, so as to increment the value of sign_count in the Causes.
    '''
    if created:
        instance.cause.sign_count += 1
        instance.cause.save()

core/forms.py
from django import forms
from .models import Causes
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
import re
from django.utils.text import slugify
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError

TAG_CHOICES = (
    ('Racism', 'Racism'),
    ('Religion', 'Religion'),
    ('Education', 'Education'),
    ('Economy', 'Economy'),
    ('Environment', 'Environment'),
)


class CauseCreateForm(forms.ModelForm):
    class Meta:
        model = Causes
        fields = ("title", "body", 'tags', 'slug')
        widgets = {
            "body": SummernoteWidget(),
            'tags': forms.CheckboxSelectMultiple(choices=TAG_CHOICES),
            # convert the tags to a multi-select field with options of the Tag-choices declared
            # above
        }

    def __init__(self, *args, **kwargs):
        # self.request = kwargs.pop('request', None)
        super(CauseCreateForm, self).__init__(*args, **kwargs)

        self.fields["title"].widget.attrs["placeholder"] = "Cause Title..."
        self.fields["title"].widget.attrs["class"] = "form-control"

    def clean_tags(self):
        '''
        The tags are not rendering well, therefore
        1. use regex to extract only words and not the symbols from the tag list
        2. convert the word into a list
        3. for each element in the list, strip out the spaces
        '''
        data = (self.cleaned_data['tags'])
        valid = re.sub(r'[^\w]', ' ', str(data))
        vd = valid.split(' ')
        delete_empty = [ele for ele in vd if ele.strip()]
        return delete_empty



    def clean_slug(self):
        '''
        This will get the slug from the title, try and see if a cause with the same slug exist
        If it exist, raise an inline form errors,
        else, assigned the slug to the new cause and return the slug
        '''
        title = self.cleaned_data['title']
        slug_title = slugify(title)
        cause = Causes.objects.filter(slug=slug_title)
        if cause.exists():
            raise ValidationError(f'Cause Title {title} exist, Change the title and Try again')
        return slug_title

class CauseUpdateForm(forms.ModelForm):
    class Meta:
        model = Causes
        fields = ("title", "body", 'tags')
        widgets = {
            "body": SummernoteWidget(),
            'tags': forms.CheckboxSelectMultiple(choices=TAG_CHOICES)
            # 'bar': SummernoteInplaceWidget(),
        }

    def clean_tags(self):
        '''
        The tags are not rendering well, therefore
        1. use regex to extract only words and not the symbols from the tag list
        2. convert the word into a list
        3. for each element in the list, strip out the spaces
        '''
        data = (self.cleaned_data['tags'])
        valid = re.sub(r'[^\w]', ' ', str(data))
        vd = valid.split(' ')
        delete_empty = [ele for ele in vd if ele.strip()]
        return delete_empty

core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from taggit.models import Tag

from .decorators import user_is_author, profile_is_edited
from .forms import CauseCreateForm, CauseUpdateForm
from .models import Causes, VoteForCause

def error_404(request, exception):
    data = {}
    return render(request, "404.html", data)


def handler500(request, *args, **argv):
    return render(request, '500.html', status=500)


def home(request):
    """
    The home view, it has the list of all causes with pagination
    """
    causes = Causes.published.all()

    paginator = Paginator(causes, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, "causes_list.html", {"causes": causes,
                                                'page_obj': page_obj, })


def search_for_cause(request):
    """
    The view for searching for cause
    """
    query = request.GET.get("query")
    if query:
        causes = Causes.published.filter(Q(title__icontains=query) | Q(body__icontains=query))

        return render(request, "search_page.html", {'causes': causes,
                                                    'query': query, })
    else:
        return render(request, 'search_page.html', {})


def user_cause(request, username):
    """
    the view to get all cause for a user passed as a url argument
    """
    # user = username
    causes = Causes.published.filter(author__username=username)

    paginator = Paginator(causes, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'user_cause.html', {'causes': causes,
                                               'user': username,
                                               'page_obj': page_obj})


def tag_view(request, tag_slug):
    """
    This will assist in filtering and listing causes by tags passed as argument using the tag_slug
    """
    causes = Causes.published.all()
    tag = get_object_or_404(Tag, slug=tag_slug)
    causes = causes.filter(tags__in=[tag])
    return render(request, "causes_list.html", {"causes": causes})


@login_required
@profile_is_edited
def create_cause(request):
    """
    In order to create a cause, the user should be authenticated, and should have edited his or
    her profile.
    if Not, will be redirected to the profile page for editing
    """
    if request.method == "POST":
        form = CauseCreateForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            cause = form.save()
            print('Slug ', cause)

            return redirect(cause.get_absolute_url())
        else:
            return render(request, "cause_create.html", {"form": form})
    else:
        form = CauseCreateForm()
    return render(request, "cause_create.html", {"form": form})


def cause_detail(request, slug):
    """
    the detail view of each cause
    """
    cause = get_object_or_404(Causes, slug=slug, active=True)
    user = request.user
    if not request.user.is_authenticated:
        has_sign = None
    else:
        has_sign = VoteForCause.objects.filter(cause=cause, user=user).exists()

    causes = Causes.published.all().order_by("-created")[:3]
    """ 
    i wrote a custom model manager published, which return the list of only published causes, 
    deleted (unpublished ) causes will be excluded.
    """

    return render(
        request,
        "cause_detail.html",
        {
            "cause": cause,
            "causes": causes,
            'has_sign': has_sign
        },
    )


@login_required
@user_is_author
def cause_update(request, slug):
    """
    User should be authenticated, and only the author of a cause can edit the cause
    """
    cause = get_object_or_404(Causes, slug=slug, active=True)
    if request.method == "POST":
        form = CauseUpdateForm(request.POST, instance=cause)
        if form.is_valid():
            form.save()
            return redirect(cause.get_absolute_url())
    else:
        form = CauseUpdateForm(instance=cause)

    return render(
        request,
        "cause_update.html",
        {
            "form": form,
        },
    )


@login_required
@user_is_author
def cause_delete(request, slug):
    """
    To delete a cause, user should be authenticated and only the author of a cause can delete a
    cause.
    Also, the cause is not deleted, but unpublished.
    """
    cause = get_object_or_404(Causes, slug=slug, active=True)
    cause.active = False
    cause.save()
    return redirect("home")


@login_required
def cause_signed_userlist(request, slug):
    """
    The view that return the list of all users that signed for a cause.
    """
    cause = get_object_or_404(Causes, slug=slug, active=True)
    vfcs = VoteForCause.objects.filter(cause=cause)

    return render(request, 'cause_signed_list.html', {'cause': cause,
                                                      'vfcs': vfcs, })


@login_required
def add_sign_cause(request, slug):
    """
    Adding signature to a cause, user should be authenticated, and cannot sign more than one.
    """
    user = request.user
    cause = get_object_or_404(Causes, slug=slug, active=True)

    vote_for_cause = VoteForCause.objects.filter(Q(cause=cause) & Q(user=user))
    if vote_for_cause.exists():
        messages.warning(request, 'You added a signature for this cause already!')
    else:
        vote_for_cause, created = VoteForCause.objects.get_or_create(cause=cause, user=user,
                                                                     has_signed=True)
        if created:
            vote_for_cause.save()

    return redirect(cause.get_absolute_url())

core/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}

    {% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
</head>
<body class="d-flex flex-column min-vh-100">
{% include 'navbar.html' %}

{% if request.path == '/' %}
    {% include 'header.html' %}
{% endif %}
    {% if messages %}
            <div class="text-center mt-0 alert alert-danger alert-dismissible fade show radius-0"
                 role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
    {% endif %}
<div class="container mt-5 pt-3">


{% block content %}
{% endblock content %}
</div>
{% include 'footer.html' %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

</body>
</html>

core/templates/cause_create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_head %}
  {{ form.media }}
{% endblock %}

{% block content %}
    <div class="col-xl-8 offset-xl-2 col-md-12 col-sm-12 mb-5">
    {% if form.errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          {% for key, error in form.errors.items %}
           {{ error | striptags }}
          {% endfor %}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    {% endif %}

    <form action="" method="post">
    {% csrf_token %}


{#    {{ form.author | as_crispy_field }}#}
    {{ form.title | as_crispy_field }}
    {{ form.tags | as_crispy_field |safe }}
    {{ form.slug.as_hidden }}
    {{ form.body | as_crispy_field |safe }}
        <input type="submit" class="btn btn-primary" value="Create Cause">
    </form>
        </div>

{% endblock %}

core/templates/cause_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="row g-5">
        <div class="col-md-8">
            {#            {% include "reading_time.html" %}#}
            {% if cause.author == request.user %}
                <a href="{% url 'update_cause' cause.slug %}">+ Edit</a>
                <a href="{% url 'delete_cause' cause.slug %}">+ Delete</a>
            {% endif %}
            <h1>{{ cause.title }}</h1>
            <p class="container blog-post-meta mb-0"> Posted {{ cause.created }} by <a href=
                                                                                               "{% url 'profile' %}">
                {{ cause.author }}</a> | <i class="fas fa-clock"></i> {{ cause.reading_time }} min
                read </p>
            <p class=" container tags">
                Tags:
                {% for tag in cause.tags.all %}
                    <a class="badge badge-primary"
                       href="{% url 'tag_view' tag.slug %}">{{ tag }}</a>
                    {#   {% if not forloop.last %}, {% endif %}#}
                {% endfor %}
            </p>
            <hr>

            <p>{{ cause.body|safe }}</p>
        <div class="col-md-10">
            <div class="row container alert alert-warning">
                <div class="col-md-8">
                    <div class="card-title m-0">
                        Start a Cause of your own
                    </div>
                    <div class="card-body p-0">
                        This cause starter stood up and took action. Will you do the same?
                    </div>
                </div>
                <div class="col-md-4 mt-3">
                    <a href="{% url 'create_cause' %}" class="btn btn-md btn-warning ">Start
                        a Cause</a>
                </div>
            </div>
            </div>
        </div>
        <div class="col-md-4">

            <div class="position-sticky" style="top: 2rem;">
                <div class="p-4 mb-3 bg-light">
                    <h4 class="fst-italic">Share:</h4>
                    <a class='btn btn-sm btn-secondary' href="//twitter
                .com/intent/tweet?text=A+New+Page&url
                ={{ request.scheme }}://{{ request.META.HTTP_HOST }}{{ request.path }}"
                       target="_blank">
                        <i class="fa-brands fa-twitter"></i>
                    </a>
                    <a class='btn btn-sm btn-secondary' href="//www.facebook.com/sharer/sharer
                .php?u={{ request.scheme }}:/
                /{{ request.META.HTTP_HOST }}{{ request.path }}" target="_blank">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class='btn btn-sm btn-secondary' href="//www.linkedin.com/cws/share?url
                ={{ request.scheme }}:/
                /{{ request.META.HTTP_HOST }}{{ request.path }}" target="_blank">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                </div>
                <div class="p-4 mb-3 bg-light">
                    <h4 class="fst-italic">Profile</h4>
                    <hr>
                    <i class="fa-solid fa-user fa-2x fa-pull-left fa-border" aria-hidden="true"></i>
                    {#                <i class="fa-solid fa-user fa-lg"></i>#}
                    <p class="mb-0">Created by: {{ cause.author }}</p>
                    <p class="mb-0">{{ cause.sign_count }} total Signatures.</p>
                    {% with cause.voteforcause_set.all as cause_vote_list %}
                        {% if not cause.sign_count == 0 %}
                            <small class="mb-0">{{ cause_vote_list.last.user | upper }} added
                                signature:
                                {{ cause_vote_list.last.time_diff }}
                            </small>
                        {% endif %}

                    {% endwith %}


                    <hr>
                    {% if not has_sign %}
                        <a class="mb-2 btn btn-info btn-block" href=
                                "{% url 'add_sign' cause.slug %}">Add your
                            signature</a>
                    {% endif %}
                    <span>
              <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: {{ cause.sign_count }}%;"
                     aria-valuenow="{{ cause.sign_count }}" aria-valuemin="0"
                     aria-valuemax="100">{{ cause.sign_count }}% signatures </div>
              </div>
      </span>
                </div>


                {#Recent causes#}
                <div class="mb-3">
                    <ul class="list-group">
                        <l1 class="list-group-item active">Recent
                            Causes
                        </l1>
                        {% for cause_obj in causes %}
                            <a href="{{ cause_obj.get_absolute_url }}"
                               class="list-group-item list-group-item-action p-2">
                                {{ cause_obj.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>

            </div>
        </div>

    </div>


{% endblock %}

core/templates/cause_signed_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-xl-8 offset-xl-2 col-md-12 col-sm-12">
        {{ cause }}
    {% for vote in vfcs %}
        {{ vote.user }}
        {% if not forloop.last %}
            ,
        {% endif %}
    {% endfor %}

    </div>

{% endblock %}

core/templates/cause_update.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="col-xl-8 offset-xl-2 col-md-12 col-sm-12 mb-5">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.title | as_crispy_field | safe }}
{#            <div class="form-check">#}
                {{ form.tags | as_crispy_field  }}
{#            </div>#}
            {{ form.body | as_crispy_field | safe }}
            <input type="submit" class='btn btn-md btn-primary' value="Update Cause">
        </form>
    </div>


{% endblock %}

core/templates/causes_list.html
{% extends "base.html" %}

{% block content %}

    <div class="mt-3 col-xl-10 offset-xl-1 col-lg-10 offset-lg-1">

        {#        <h1 class="display-4">Recent Causes</h1>#}
        {% for cause in page_obj %}
            <div class="card  mb-4">
                <div class="card-body">
                    <h2 class="blog-post-title">
                        <a href="{{ cause.get_absolute_url }}">{{ cause.title }}</a>
                    </h2>
                    <p class="blog-post-meta">{{ cause.created }} by <a href="
{% url 'user_cause' cause.author.username %}"><strong>{{ cause.author }}</strong></a></p>
                    <p class="tags">
                        Tags:
                        {% for tag in cause.tags.all %}
                            <a class="badge badge-primary"
                               href="{% url 'tag_view' tag.slug %}">{{ tag }}</a>
                        {% endfor %}
                    </p>
                    <p class="card-text">{{ cause.body | truncatewords:30 | safe }}</p>

                    <span>
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: {{ cause.sign_count }}%;"
                 aria-valuenow="{{ cause.sign_count }}" aria-valuemin="0"
                 aria-valuemax="100">{{ cause.sign_count }}% signed </div>
        </div>
      </span>

                </div>
            </div>
        {% endfor %}
    </div>

    {% if page_obj.has_other_pages %}
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link">Page {{ page_obj.number }} of
                    {{ page_obj.paginator.num_pages }}</a>
            </li>
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link {% if page_obj == 1 %} disabled {% endif %}" href="?page=1">&laquo;
                        1</a>
                </li>
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% endif %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last
                        &raquo;</a>
                </li>
            {% endif %}
        </ul>
    {% endif %}


{% endblock %}

core/templates/footer.html
<footer class="blog-footer mt-auto">
  <p>Built with &hearts; &hearts; by <a href="https://linkedin.com/lawal-afeez">Lawal Afeez</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

core/templates/header.html
<div class="jumbotron rounded-0 mb-0">
    <div class="container text-center">
        <h1 style="font-size:4vw;">The world’s platform for making positive changes with your
            Signature.</h1>
        <p class="lead"></p>
        <hr class="my-4">
        <p></p>
            <p class="lead">
            <a class="btn btn-danger btn-md" href="{% url 'create_cause' %}" role="button">Start a
                Cause</a>
        </p>

    </div>
</div>

core/templates/home.html
{% extends "base.html" %}

{% block content %}

<h2>Welcome to the homepage</h2>

{{ request.user.username }}
{% endblock %}

core/templates/navbar.html
{% url 'home' as home %}
{% url 'search' as search %}
{% url 'account_login' as login %}
{% url 'account_logout' as logout %}
{% url 'account_signup' as register %}
{% url 'create_cause' as cause_create %}
{% url 'profile' as profile %}
{% url 'user_cause' as user_cause %}


<nav class="navbar navbar-expand-lg navbar-expand navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Cause</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item {% if request.path == cause_create %} active {% endif %}">
                            <a class="nav-link" href="{% url 'create_cause' %}">Create</a>
                        </li>
                        <li class="nav-item {% if request.path == profile %} active {% endif %}">
                            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                        </li>
{#                        <li class="nav-item {% if request.path == user_cause %} active {% endif %}">#}
{#                            <a class="nav-link" href="{% url 'user_cause' request.user %}">My Cause</a>#}
{#                        </li>#}
                    </ul>
                    <ul class="navbar-nav mr">
                    <li class="nav-item {% if request.path == user_cause %} active {% endif %}">
                            <a class="nav-link" href="{% url 'user_cause' request.user %}">My Cause</a>
                        </li>
                        <li class="nav-item {% if request.path == logout %} active {% endif %}">
                            <a class="nav-link "
                               href="{% url 'account_logout' %}">Logout</a>
                        </li>
                    {% if request.path == '/' %}
                        <li class="nav-item {% if request.path == search %}active{% endif %}">
                            <a class="nav-link" href="{% url 'search' %}"><i class="fa fa-search"></i></a>
                        </li>
                    {% endif %}

                    </ul>

                {% else %}
                    <ul class="navbar-nav mr-auto">

                        <li class="nav-item {% if request.path == login %} active {% endif %}">
                            <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                        </li>
                        <li class="nav-item {% if request.path == register %} active {% endif %}">
                            <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                        </li></ul>
                    <ul class="navbar-nav ml">
                        {% if request.path == '/' %}
                            <li class="nav-item {% if request.path == search %}active{% endif %}">
                                <a class="nav-link" href="{% url 'search' %}"><i class="fa fa-search"></i></a>
                            </li>
                    {% endif %}
                    </ul>

                {% endif %}

        </div>

    </div>
</nav>

core/templates/search.html
<form action="" method="get">
    <div class="input-group py-1 px-2 px-md-0">
        <input class="form-control form-control-dark" name='query' type="text"
               placeholder="Search for cause..."
               aria-label="Search">
        <div class="input-group-append">
            <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i>
            </button>
        </div>
    </div>
</form>